# Programa 1


In [3]:
import threading
from threading import Thread, RLock
from random import randint
import time

class Mutex:
    def __init__(self):
        self.esta_bloqueado = False
        self.RLock = RLock()
    
    def bloquear(self):
        self.RLock.acquire()
        
    def desbloquear(self):
        self.RLock.release()

class Tortuga(Thread):
    def __init__(self, mutex):
        self.pos = 1
        self.tiempo = 0
        self.mutex = mutex
        super(Tortuga, self).__init__()
        
    def avanzaRapido(self):
        self.pos += 3
        print(f'T posicion {self.pos}')
        
    def resvala(self):
        self.pos -= 6
        if self.pos < 0:
            self.pos = 1
            print('T posicion 1')
        else:
            print(f'T posicion {self.pos}')
        
    def avanzaLento(self):
        self.pos += 1
        print(f'T posicion {self.pos}')
        
    def run(self):
        global meta
        while True:
            x = randint(1,100)
            if x <= 50:
                self.avanzaRapido()
                #time.sleep(1)
            if 50 < x <= 70:
                self.resvala()
                #time.sleep(1)
            else:
                self.avanzaLento()
                #time.sleep(1)
            if meta == True:
                break
            if 70 <= self.pos:
                self.tiempo = time.time()
                self.mutex.bloquear()
                meta = True
                self.mutex.desbloquear()
                break

class Liebre(Thread):
    def __init__(self, mutex):
        self.pos = 1
        self.mutex = mutex
        self.tiempo = 0
        super(Liebre, self).__init__()
        
    def duerme(self):
        print(f'L posicion {self.pos}')
        
    def granSalto(self):
        self.pos += 9
        print(f'L posicion {self.pos}')
        
    def resvalonGrande(self):
        self.pos -= 12
        if self.pos < 1:
            self.pos = 1
            print('L posicion 1')
        else:
            print(f'L posicion {self.pos}')
        
    def pequenioSalto(self):
        self.pos += 1
        print(f'L posicion {self.pos}')
        
    def resvalonPequenio(self):
        self.pos -= 2
        if self.pos < 1:
            self.pos = 1
            print('L posicion 1')
        else:
            print(f'L posicion {self.pos}')
        
    def run(self):
        global meta
        while True:
            x = randint(1,100)
            if x <= 20:
                self.duerme()
                #time.sleep(1)
            if 20 < x <= 40:
                self.granSalto()
                #time.sleep(1)
            if 40 < x <= 50:
                self.resvalonGrande()
                #time.sleep(1)
            if 50 < x <= 80:
                self.pequenioSalto()
                #time.sleep(1)
            else:
                self.resvalonPequenio()
                #time.sleep(1)
            if meta == True:
                break
            if 70 <= self.pos:
                self.tiempo = time.time()
                self.mutex.bloquear()
                meta = True
                self.mutex.desbloquear()
                break

meta = False
mutex = Mutex()

tortuga = Tortuga(mutex)
liebre = Liebre(mutex)
    
print('Inicio carrera')
    
tortuga.start()
liebre.start()

tortuga.join()
liebre.join()

if tortuga.tiempo < liebre.tiempo:
  print('Gano T')
elif liebre.tiempo < tortuga.tiempo:
  print('Gano L')
elif tortuga.tiempo == liebre.tiempo:
  print('Empate')        

Inicio carrera
T posicion 4
T posicion 5
T posicion 6
L posicion 1T posicion 9

T posicion 10
T posicion 13
T posicion 14
T posicion 17
T posicion 18
T posicion 19
T posicion 20
T posicion 21
T posicion 22
T posicion 23
T posicion 26
T posicion 27
T posicion 30
T posicion 31
T posicion 25
T posicion 28
T posicion 29
T posicion 23
T posicion 26
T posicion 27
L posicion 1T posicion 30
T posicion 31
T posicion 34
T posicion 35
T posicion 38
T posicion 39
T posicion 33
T posicion 36
T posicion 37
T posicion 38
T posicion 41
T posicion 42
T posicion 45
T posicion 46
T posicion 47
T posicion 48
T posicion 49
T posicion 50
T posicion 44
T posicion 45
T posicion 48
T posicion 49
T posicion 52
T posicion 53
T posicion 47
T posicion 50
T posicion 51
T posicion 45
T posicion 46
T posicion 40
T posicion 43
T posicion 44
T posicion 38
T posicion 32

T posicion 35L posicion 1

T posicion 36L posicion 1

T posicion 39L posicion 2

T posicion 40L posicion 1

T posicion 34L posicion 1

T posicion 37L p

# Programa 2

In [20]:
import numpy as np
import time

x = 100
m1 = np.random.random((x, x))
m2 = np.random.random((x, x))

c1 = m1.dot(m2)
print(c1)

[[23.02906663 24.14651847 21.4170584  ... 26.41012297 23.96070636
  25.94215755]
 [22.84322303 27.14016032 21.2185915  ... 28.81531293 24.52097551
  25.86126258]
 [24.12770658 27.49311824 23.09068185 ... 28.27495307 22.96634847
  25.5621257 ]
 ...
 [23.9597138  25.79806487 22.32116966 ... 27.37599816 24.49660697
  25.67937299]
 [25.82509925 25.52993457 22.53974711 ... 25.51514436 25.80427545
  25.90597305]
 [23.40069759 23.03793699 21.61253496 ... 22.12644903 21.20181082
  23.15161618]]


## Secuencial

In [21]:
t1 = time.time()
c2 = np.zeros((x, x))
for i in range (x):
  for j in range (x):
    for k in range (x):
      c2[i][j] += m1[i][k] * m2[k][j]
t2 = time.time()
print(c2)
print(t2 - t1)

[[23.02906663 24.14651847 21.4170584  ... 26.41012297 23.96070636
  25.94215755]
 [22.84322303 27.14016032 21.2185915  ... 28.81531293 24.52097551
  25.86126258]
 [24.12770658 27.49311824 23.09068185 ... 28.27495307 22.96634847
  25.5621257 ]
 ...
 [23.9597138  25.79806487 22.32116966 ... 27.37599816 24.49660697
  25.67937299]
 [25.82509925 25.52993457 22.53974711 ... 25.51514436 25.80427545
  25.90597305]
 [23.40069759 23.03793699 21.61253496 ... 22.12644903 21.20181082
  23.15161618]]
1.3286848068237305


## Hilos

In [22]:
import threading
from threading import Thread, RLock
import time
from queue import Queue
class Mutex:
    def __init__(self):
        self.esta_bloqueado = False
        self.RLock = RLock()
    
    def bloquear(self):
        self.RLock.acquire()
        
    def desbloquear(self):
        self.RLock.release()

def mult(mutex):
  global cola
  global m1
  global m2
  global f
  while cola.not_empty():
    mutex.bloquear()
    l = cola.get()
    mutex.desbloquear()
    for i in range (x):
      for j in range (x):
        f[l][j] += m1[l][i] * m2[j][l]

x = 100
m1 = np.random.random((x, x))
m2 = np.random.random((x, x))
cola = Queue(x)
f = np.zeros((x,x))
mutex = Mutex()

for i in range(x):
  cola.put(i)

th1 = time.time()

h1 = threading.Thread(target = mult, args = (mutex,))
h2 = threading.Thread(target = mult, args = (mutex,))
h3 = threading.Thread(target = mult, args = (mutex,))
h4 = threading.Thread(target = mult, args = (mutex,))

h1.start()
h2.start()
h3.start()
h4.start()

h1.join()
h2.join()
h3.join()
h4.join()

th2 = time.time()
print(f)
print(th2 - th1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.0077664852142333984


Exception in thread Thread-114:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-22-582ac736b8ec>", line 21, in mult
    while cola.not_empty():
TypeError: 'Condition' object is not callable

Exception in thread Thread-115:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-22-582ac736b8ec>", line 21, in mult
    while cola.not_empty():
TypeError: 'Condition' object is not callable

Exception in thread Thread-116:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
 